apiVersion: apps/v1
kind: Deployment
metadata:
  name: graduate-placement-api
  labels:
    app: graduate-placement-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graduate-placement-api
  template:
    metadata:
      labels:
        app: graduate-placement-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: graduate-placement-api
          image: graduate-placement:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: "/app/models/xgb_model.pkl"
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: graduate-placement-secret
                  key: API_TOKEN
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: graduate-placement-config
                  key: APP_NAME
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: graduate-placement-config
                  key: APP_ENV
          volumeMounts:
            - name: model-volume
              mountPath: /app/models/
      volumes:
        - name: model-volume
          hostPath:
            path: /app/models/
---
apiVersion: v1
kind: Service
metadata:
  name: graduate-placement-service
spec:
  type: NodePort
  selector:
    app: graduate-placement-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30087
